### ISSUE TITLE
Add a Jaeger lab using OpenLiberty Microprofile

### ISSUE THREAD

**Issue by csantanapr** [ibm-cloud-architecture/learning-distributed-tracing-101#3]
We have spring boot covered, but we are lacking a lab that shows how to instrument a microprofile java app with opentracing and jaeger

@nastacio is giving a talk and will be contributing this lab 🙌 
https://twitter.com/dnastacio/status/1233151298679328768?s=20

**Comment by nastacio** [comment]
@csantanapr , with the new lab being written in Java and the existing Spring Boot already being called "Java", do you have suggestions on the name for the new lab?

I am thinking of "jee" or "openliberty" and would welcome your thoughts.

PS: I am making good progress with it and already have the Open Liberty application up and running.

**Comment by csantanapr** [comment]
Good question “jee” might scare new comers 
“openliberty” is ok
