### ISSUE TITLE
Using git clone with ssh give errors in OpenLiberty Istio Lab

### ISSUE THREAD

**Issue by csantanapr** [ibm-cloud-architecture/learning-distributed-tracing-101#6]
Using git clone with ssh give errors in OpenLiberty Istio Lab https://ibm-cloud-architecture.github.io/learning-distributed-tracing-101/docs/ocp-istio-ol.html

To reproduce

Instead of git clone with https the user might use ssh
```
git clone git@github.com:ibm-cloud-architecture/learning-distributed-tracing-101.git
cd learning-distributed-tracing-101
```

```
oc new-build . --strategy=docker --context-dir=lab-jaeger-istio-ol/service-a --name service-a-openliberty-istio
```

```
oc logs -f bc/service-a-openliberty-istio
```

Error:

```
Cloning "git@github.com:ibm-cloud-architecture/learning-distributed-tracing-101.git" ...
error: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

We should add a note for the user, if they see this error on how to delete the buildconfig, and to use git clone with https and try again.

**Comment by csantanapr** [comment]
@nastacio 
I was able to reproduce the problem with ssh clone

**Comment by csantanapr** [comment]
To clean
```
oc delete buildconfig service-a-openliberty-istio -n default
oc delete imagestream open-liberty -n default
```

**Comment by nastacio** [comment]
@csantanapr thanks for recreating it, I will take this issue.
I also want to research whether it is possible to solve the error by setting keys somewhere.

**Comment by csantanapr** [comment]
Yes you can can create OpenShift secret with git ssh secrets

**Comment by csantanapr** [comment]
I think this are the steps
https://blog.openshift.com/private-git-repositories-part-2a-repository-ssh-keys/

**Comment by nastacio** [comment]
Ultimately I went with the caution about the usage of `https`. It is good to know it is relatively easy to setup the ssh keys, but too much of a distraction for the topic at hand to support both protocols in the instructions, especially for a public GH repo.

**Comment by csantanapr** [comment]
@nastacio yes I agree 
Could send a PR? to this repository with the changes you here https://github.com/nastacio/learning-distributed-tracing-101/commit/ee1096109a117b8a24971ce3cd9205a4af998271
